version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11  
      terraform: 0.14.5  # Specify Terraform version (if required)
    commands:
      - echo "Installing unzip and Terraform"
      - yum install -y unzip
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.14.5/terraform_0.14.5_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/

  pre_build:
    commands:
      - echo "Fetching ZIP file from S3"
      - aws s3 cp s3://your-bucket-name/path-to-your-zip.zip .
      - unzip path-to-your-zip.zip
      - cd extracted-folder  # Move to the extracted folder where the Python script is

  build:
    commands:
      - echo "Running Python script to execute Terraform commands"
      - python3 your_script.py  # Ensure your script contains the logic for Terraform commands

artifacts:
  files:
    - '**/*'  # This allows you to save the outputs if needed
  discard-paths: yes
